import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import * as api from '../../api/endpoints.js';
import { CompassIcon, DatabaseOffIcon } from '../ui/Icons.jsx';
import { Badge } from '../ui/Badge.jsx';

/** Footer, live service status, and required data attribution. */
export default function Footer() {
  const { data: config } = useQuery({
    queryKey: api.keys.config,
    queryFn: api.getServerConfig,
    staleTime: 10 * 60 * 1000,
    retry: false,
  });

  const accountsOffline = config && config.features?.accounts === false;

  return (
    <footer className="mt-20 bg-brand-950 text-stone-300">
      {accountsOffline ? (
        <div className="border-b border-amber-400/25 bg-amber-300 text-amber-950">
          <div className="tm-shell flex items-start gap-2.5 py-3 text-xs leading-5">
            <DatabaseOffIcon className="mt-0.5 size-4 shrink-0" />
            <span>
              Running in degraded mode: the database is unreachable, so sign-in and saved trips are
              unavailable. Planning, weather, places and currency all still work.
            </span>
          </div>
        </div>
      ) : null}

      <div className="tm-shell py-12 sm:py-16">
        <div className="grid gap-10 border-b border-white/12 pb-12 lg:grid-cols-[1.4fr_0.55fr_1fr]">
          <div className="max-w-xl">
            <Link to="/" className="inline-flex items-center gap-3 text-white">
              <span className="grid size-11 place-items-center rounded-full border border-white/20 bg-white/8">
                <CompassIcon className="size-5" />
              </span>
              <span className="tm-display text-3xl">TrailMate</span>
            </Link>
            <p className="tm-display mt-6 max-w-lg text-3xl leading-tight text-stone-100 sm:text-4xl">
              One thoughtful view for the whole journey.
            </p>
            <p className="mt-5 max-w-lg text-sm leading-7 text-stone-400">
              Weather, places, currency, country facts and a grounded travel briefing, brought
              together without exposing a single provider key in your browser.
            </p>

            {config ? (
              <div className="mt-6 flex flex-wrap gap-2">
                <Badge tone="neutral" title="Weather provider in use">
                  weather: {config.providers?.weather}
                </Badge>
                <Badge tone="neutral" title="Places provider in use">
                  places: {config.providers?.places}
                </Badge>
                <Badge
                  tone={config.ai?.configured ? 'brand' : 'neutral'}
                  title={
                    config.ai?.configured
                      ? `AI briefings generated by ${config.ai.provider}`
                      : 'No LLM configured — briefings use the deterministic rule engine'
                  }
                >
                  ai: {config.ai?.provider}
                </Badge>
              </div>
            ) : null}
          </div>

          <nav aria-label="Footer" className="text-sm">
            <p className="text-[0.65rem] font-bold uppercase tracking-[0.2em] text-stone-500">
              Explore
            </p>
            <ul className="mt-4 space-y-3">
              <li>
                <Link className="transition-colors hover:text-white" to="/">
                  Plan a trip
                </Link>
              </li>
              <li>
                <Link className="transition-colors hover:text-white" to="/multi-city">
                  Multi-city route
                </Link>
              </li>
              <li>
                <Link className="transition-colors hover:text-white" to="/trips">
                  Saved trips
                </Link>
              </li>
              <li>
                <Link className="transition-colors hover:text-white" to="/settings">
                  Preferences
                </Link>
              </li>
            </ul>
          </nav>

          <div className="text-xs leading-6 text-stone-400">
            <p className="text-[0.65rem] font-bold uppercase tracking-[0.2em] text-stone-500">
              Trusted data sources
            </p>
            <ul className="mt-4 grid gap-x-6 gap-y-2 sm:grid-cols-2 lg:grid-cols-1">
              <li>
                Weather ·{' '}
                <a
                  className="text-stone-200 hover:underline"
                  href="https://open-meteo.com/"
                  target="_blank"
                  rel="noreferrer noopener"
                >
                  Open-Meteo
                </a>{' '}
                /{' '}
                <a
                  className="text-stone-200 hover:underline"
                  href="https://openweathermap.org/"
                  target="_blank"
                  rel="noreferrer noopener"
                >
                  OpenWeatherMap
                </a>
              </li>
              <li>
                Places · ©{' '}
                <a
                  className="text-stone-200 hover:underline"
                  href="https://www.openstreetmap.org/copyright"
                  target="_blank"
                  rel="noreferrer noopener"
                >
                  OpenStreetMap contributors
                </a>{' '}
                &{' '}
                <a
                  className="text-stone-200 hover:underline"
                  href="https://en.wikipedia.org/"
                  target="_blank"
                  rel="noreferrer noopener"
                >
                  Wikipedia
                </a>
              </li>
              <li>
                Rates ·{' '}
                <a
                  className="text-stone-200 hover:underline"
                  href="https://frankfurter.app/"
                  target="_blank"
                  rel="noreferrer noopener"
                >
                  Frankfurter
                </a>{' '}
                (ECB reference rates)
              </li>
              <li>
                Countries ·{' '}
                <a
                  className="text-stone-200 hover:underline"
                  href="https://github.com/mledoze/countries"
                  target="_blank"
                  rel="noreferrer noopener"
                >
                  mledoze/countries
                </a>
              </li>
            </ul>
          </div>
        </div>

        <div className="flex flex-col gap-3 pt-6 text-[0.68rem] leading-5 text-stone-500 sm:flex-row sm:items-start sm:justify-between">
          <p className="max-w-3xl">
            Budget figures are transparent estimates, not live pricing. Forecasts and opening hours
            should be re-checked before you travel.
          </p>
          <p className="shrink-0">TrailMate{config?.version ? ` · API v${config.version}` : ''}</p>
        </div>
      </div>
    </footer>
  );
}
